# Generated by Django 4.1.3 on 2022-12-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jecalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jecalc',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jecalc',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jecalc',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jecalc',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
