# Generated by Django 4.1.3 on 2022-12-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jecalc_email_jecalc_lastname_jecalc_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jecalc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jecalc',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='jecalc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jecalc',
            name='phone',
        ),
    ]
