# Generated by Django 4.1.3 on 2022-12-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_jecalc_email_remove_jecalc_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jecalc',
            name='sel',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
