# Generated by Django 4.1.3 on 2022-12-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_jecalc_sel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jecalc',
            name='labour',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
