# Generated by Django 4.1.3 on 2022-12-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_bill_cus_id_alter_bill_date_alter_bill_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='email',
            new_name='bemail',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='name',
            new_name='bname',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='phone',
            new_name='bphone',
        ),
    ]
