# Generated by Django 4.1.3 on 2022-12-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qrimages',
            field=models.ImageField(default='', upload_to='static/qrimages/'),
        ),
    ]
